xxxpeers limit config parse & bug fix
FISCO-BCOS/FISCO-BCOS pull request #2404
Opened 2022-04-28 11:09 UTC by luyikang-York

1.xxxpeers limit config parse : 
peers param limit
max nodes limit

2. Spelling mistakes
 faield =>failed

2022-04-28 11:49 UTC, luyikang-York commented
issue #2403 solved by the way

2022-04-28 13:31 UTC, ywy2090 requested changes

2022-04-28 13:39 UTC, luyikang-York commented on libinitializer/P2PInitializer.cpp
> +    int maxNodesLimit = _pt.get<int>("p2p.max_nodes_linit", 100);
yes

2022-05-09 04:24 UTC, ywy2090 approved these changes

2022-05-09 04:24 UTC, merged