Optimize SyncPeerStatus lock range
FISCO-BCOS/FISCO-BCOS pull request #3650
Opened 2023-05-24 06:28 UTC by chuwen95

2023-05-24 07:45 UTC, kyonRay approved these changes

2023-05-24 07:45 UTC, kyonRay approved these changes

2023-05-25 01:52 UTC, JimmyShi22 approved these changes

2023-05-25 02:33 UTC, bxq2011hust requested changes

2023-05-25 02:33 UTC, bxq2011hust commented on bcos-sync/bcos-sync/state/SyncPeerStatus.cpp
> +        if (m_peersStatus.contains(_peer))
use find instead of contains, contains and [] will find twice

2023-05-25 02:38 UTC, bxq2011hust commented on bcos-sync/bcos-sync/state/SyncPeerStatus.cpp
> +        ReadGuard lock(x_peersStatus);
if peerStatus will not be frequent updated, use std::mutex will have better performance

2023-05-25 02:50 UTC, chuwen95 commented on bcos-sync/bcos-sync/state/SyncPeerStatus.cpp
> +        ReadGuard lock(x_peersStatus);
> if peerStatus will not be frequent updated, use std::mutex will have better performance

每200ms会有一个节点状态包，应该还是比较频繁的，这个先不改？

2023-05-25 05:57 UTC, kyonRay commented on bcos-sync/bcos-sync/state/SyncPeerStatus.cpp
> +        ReadGuard lock(x_peersStatus);
下个PR我会修改peerStatus的的广播逻辑，降低频率。这个地方我下个PR再修改。

2023-05-25 07:55 UTC, bxq2011hust approved these changes

2023-05-25 07:56 UTC, merged