Feature billing
FISCO-BCOS/FISCO-BCOS pull request #4031
Opened 2023-11-08 11:22 UTC by Mojicode

2023-11-09 01:37 UTC, JimmyShi22 submitted a review, later dismissed

2023-11-10 01:53 UTC, JimmyShi22 approved these changes

2023-11-10 06:30 UTC, bxq2011hust commented on bcos-executor/src/executive/BillingTransactionExecutive.cpp
> +#ifdef WITH_WASM
```suggestion

```

2023-11-10 07:01 UTC, bxq2011hust requested changes

2023-11-10 07:09 UTC, bxq2011hust commented on bcos-executor/src/executive/ExecutiveSerialFlow.cpp
> +    return m_executiveFactory->build(input->codeAddress, input->contextID, input->seq, ExecutiveType::billing);
```suggestion
    return m_executiveFactory->build(input->codeAddress, input->contextID, input->seq, ExecutiveType::common);
```
看其他代码，这里应该是common吧？

2023-11-10 07:11 UTC, Mojicode commented on bcos-executor/src/executive/ExecutiveSerialFlow.cpp
> +    return m_executiveFactory->build(input->codeAddress, input->contextID, input->seq, ExecutiveType::billing);
不是的，就是在这个串行flow里面要使用新的billing功能的executive

2023-11-10 07:12 UTC, Mojicode commented on bcos-executor/src/executive/BillingTransactionExecutive.cpp
> +#ifdef WITH_WASM
已经删除了，还包括ifdef下面的endif

2023-11-10 07:55 UTC, bxq2011hust commented on bcos-executor/src/executive/ExecutiveSerialFlow.cpp
> +    return m_executiveFactory->build(input->codeAddress, input->contextID, input->seq, ExecutiveType::billing);
那应该要使用feature功能控制默认不开启？

2023-11-10 08:05 UTC, JimmyShi22 approved these changes

2023-11-10 08:10 UTC, bxq2011hust submitted a review, later dismissed

2023-11-10 09:01 UTC, morebtcg approved these changes

2023-11-10 09:01 UTC, JimmyShi22 approved these changes

2023-11-10 09:39 UTC, merged