Add code for balance transfer,include transfer, getBalance, suicide
FISCO-BCOS/FISCO-BCOS pull request #4033
Opened 2023-11-09 05:50 UTC by yongmi2662

2023-11-09 06:12 UTC, JimmyShi22 commented on bcos-executor/src/executive/TransactionExecutive.cpp
> +    // to aub balance
```suggestion
bool TransactionExecutive::transferBalance(std::string_view origin,std::string_view sender, 
    std::string_view receiver, const s256& value, int64_t gas)
{
    // to sub balance
```

2023-11-09 06:15 UTC, JimmyShi22 commented on bcos-executor/src/executive/TransactionExecutive.cpp
> +    int64_t gas = callParameters->gas;
这个地方调用比较频繁，可以考虑性能。把这些参数直接传到下面的函数里，少一次构造string

2023-11-09 06:24 UTC, JimmyShi22 commented on bcos-executor/src/executive/TransactionExecutive.cpp
> +
转账操作在参考以太坊，在调用Precompiled的前面：
https://github.com/ethereum/go-ethereum/blob/470dba8fc1890938a65bbf4293a4759a9b9615a1/core/vm/evm.go#L208-L227

这里可以放到`if (callParameters->create) `的前面

2023-11-09 11:03 UTC, JimmyShi22 commented on bcos-executor/src/executive/TransactionExecutive.cpp
> +    std::string_view receiver, const s256& value, int64_t gas)
```suggestion
    std::string_view receiver, const u256& value, int64_t gas)
```

2023-11-09 11:03 UTC, JimmyShi22 commented on bcos-executor/src/executive/TransactionExecutive.h
> +        std::string_view receiver, const s256& value, int64_t gasLeft);
```suggestion
        std::string_view receiver, const u256& value, int64_t gasLeft);
```

2023-11-09 11:05 UTC, JimmyShi22 approved these changes

2023-11-10 06:19 UTC, bxq2011hust commented on bcos-executor/src/vm/EVMHostInterface.cpp
> +            BOOST_THROW_EXCEPTION(bcos::protocol::PrecompiledError("call AccountPrecompiled to get balance failed"));
please add ut for this exception

2023-11-10 06:21 UTC, bxq2011hust commented on bcos-executor/src/vm/EVMHostInterface.cpp
> +        bytes result = bytes(output.output_data, output.output_data + sizeof(output.output_data));
should use output.output_size

2023-11-10 06:28 UTC, bxq2011hust requested changes

2023-11-10 06:28 UTC, bxq2011hust commented on bcos-executor/src/vm/EVMHostInterface.cpp
> +            BOOST_THROW_EXCEPTION(bcos::protocol::PrecompiledError("selfdestruct ,call AccountPrecompiled to get balance failed"));
add ut for this exception

2023-11-10 06:28 UTC, bxq2011hust commented on bcos-executor/src/vm/EVMHostInterface.cpp
> +            BOOST_THROW_EXCEPTION(bcos::protocol::PrecompiledError("selfdestruct ,call AccountPrecompiled to subAccountBalance(uint256) failed"));
add ut for this exception

2023-11-10 06:28 UTC, bxq2011hust commented on bcos-executor/src/vm/EVMHostInterface.cpp
> +            BOOST_THROW_EXCEPTION(bcos::protocol::PrecompiledError("selfdestruct ,call AccountPrecompiled to addAccountBalance(uint256) failed"));
add ut for this exception

2024-01-28 14:21 UTC, closed without merging