upgrade evm to cancun
FISCO-BCOS/FISCO-BCOS pull request #4332
Opened 2024-03-28 08:31 UTC by wenlinlee

2024-04-29 01:44 UTC, bxq2011hust commented on bcos-executor/src/executor/TransactionExecutor.cpp
> +        return FiscoBcosScheduleCanCun;
```suggestion
        return FiscoBcosScheduleCancun;
```

2024-04-29 01:48 UTC, bxq2011hust requested changes

2024-04-29 01:48 UTC, bxq2011hust commented on bcos-executor/src/executive/TransactionExecutive.h
> +        m_transientRecoder = std::make_shared<storage::Recoder>();
construct m_transientRecoder before it is used

2024-04-29 01:54 UTC, bxq2011hust commented on bcos-executor/src/vm/Precompiled.cpp
> +// static inline ALWAYS_INLINE void sha_256_implementation(uint32_t h[8], const void* input, size_t
add a new file to put 0xa implement

2024-04-29 01:56 UTC, bxq2011hust commented on bcos-executor/src/vm/VMInstance.cpp
> +        *_msg, m_revision, *_hostContext.interface, &_hostContext, m_code, data);
```suggestion
        *_msg, m_revision, *_hostContext.interface, &_hostContext, m_code, {});
```

2024-04-29 01:57 UTC, bxq2011hust commented on bcos-executor/src/vm/HostContext.h
> +    evmc_bytes32 storeTransient(const evmc_bytes32* key);
```suggestion
    evmc_bytes32 getTransient(const evmc_bytes32* key);
```

2024-04-29 02:01 UTC, bxq2011hust commented on bcos-executor/src/vm/EVMHostInterface.cpp
> +    if (value == 0)  // TODO: Should use 32 bytes 0
delete this, the code is useless

2024-04-29 03:24 UTC, wenlinlee commented on bcos-executor/src/vm/Precompiled.cpp
> +// static inline ALWAYS_INLINE void sha_256_implementation(uint32_t h[8], const void* input, size_t
next pr

2024-04-29 06:13 UTC, bxq2011hust commented on bcos-executor/src/vm/HostContext.h
> +    void setTransientStore(const evmc_bytes32* key, const evmc_bytes32* value);
```suggestion
    void setTransient(const evmc_bytes32* key, const evmc_bytes32* value);
```

2024-04-29 06:20 UTC, bxq2011hust commented on bcos-executor/src/vm/HostContext.cpp
> +void HostContext::setTransientStore(const evmc_bytes32* key, const evmc_bytes32* value)
```suggestion
void HostContext::setTransient(const evmc_bytes32* key, const evmc_bytes32* value)
```

2024-04-29 06:20 UTC, bxq2011hust submitted a review, later dismissed

2024-04-29 06:35 UTC, morebtcg submitted a review, later dismissed

2024-04-29 06:54 UTC, morebtcg submitted a review, later dismissed

2024-05-08 06:04 UTC, kyonRay submitted a review, later dismissed

2024-05-10 06:59 UTC, morebtcg submitted a review, later dismissed

2024-05-10 09:30 UTC, JimmyShi22 commented on bcos-executor/src/executive/BlockContext.cpp
> +    }
```suggestion
    if (m_features.get(ledger::Features::Flag::feature_evm_cancun))
    {
        m_schedule = FiscoBcosScheduleCancun;
    }
    else if (blockVersion >= (uint32_t)bcos::protocol::BlockVersion::V3_2_VERSION)
    {
        m_schedule = FiscoBcosScheduleV320;
    } else 
    {
        m_schedule = FiscoBcosSchedule;
    }
```

2024-05-10 09:30 UTC, JimmyShi22 commented on bcos-executor/src/executive/BlockContext.cpp
> +    }
封装一个函数，复用之前的逻辑

2024-05-10 10:41 UTC, wenlinlee commented on bcos-executor/src/Common.h
> +    schedule.enableCanCun = true;
这里我理解标志位是代表使用哪个版本，用于判断toversion函数里面返回的版本号，enableCanCun位true就代表version是cancun，enablePairs为true就代表所用版本为巴黎

2024-05-10 10:43 UTC, wenlinlee commented on bcos-executor/src/executor/TransactionExecutor.cpp
> +    task::syncWait(features.readFromStorage(*m_backendStorage, m_lastCommittedBlockNumber + 1));
这里已去掉

2024-05-10 10:45 UTC, wenlinlee commented on bcos-executor/src/executive/TransactionExecutive.cpp
> +std::shared_ptr<storage::StateStorageInterface> TransactionExecutive::getTransientStateStorage(
把此函数放至BlockContext，在TransactionExecutive无法被调用

2024-05-13 01:36 UTC, bxq2011hust commented on bcos-executor/src/executive/BlockContext.cpp
> +    m_transientStorageMap(std::make_shared<transientStorageMap>(10)),
why not use std::map?
the transientStorage's lifetime is tx, every tx has its transientStorage. I think we don't need to consider parallel

2024-05-21 08:45 UTC, bxq2011hust approved these changes

2024-05-21 09:42 UTC, morebtcg approved these changes

2024-05-21 10:57 UTC, kyonRay approved these changes

2024-05-21 11:58 UTC, merged