<feat>(rpc): implement ethereum filter related interfaces (newBlockFilter, newPendingTxFilter, newFilter, uninstallFilter, getFilterChanges, getFilterLogs, getLogs)
FISCO-BCOS/FISCO-BCOS pull request #4412
Opened 2024-04-26 06:01 UTC by jdkuangxx

实现以太坊过滤器相关接口（newBlockFilter、newPendingTxFilter、newFilter、uninstallFilter、getFilterChanges、getFilterLogs、getLogs）

2024-04-26 07:47 UTC, kyonRay requested changes

2024-04-26 07:47 UTC, kyonRay commented on bcos-rpc/bcos-rpc/filter/FilterRequest.cpp
> +static inline std::string removePrefix(std::string&& str)
not need removePrefix?

2024-04-26 07:47 UTC, kyonRay commented on bcos-rpc/bcos-rpc/filter/FilterSystem.h
> +            item.second->cancelDeadLineTimer();
没有一个filter维护一个时间，可以整个系统维护一个timer，超时就丢掉

2024-04-26 07:47 UTC, kyonRay commented on bcos-rpc/bcos-rpc/filter/FilterSystem.cpp
> +    co_return std::string();
double return

2024-04-26 07:47 UTC, kyonRay commented on bcos-rpc/bcos-rpc/filter/FilterSystem.cpp
> +            jRes.append(toHexStringWithPrefix(block->transactionMetaData(index)->hash()));
取的交易哈希不在transactionMetaData里，在transactionHash里

2024-04-26 07:47 UTC, kyonRay commented on bcos-rpc/bcos-rpc/filter/FilterSystem.h
> +    int m_filterTimeout = 5 * 60;  // s
考虑内存对齐，可以省8个字节

2024-04-28 06:42 UTC, jdkuangxx commented on bcos-rpc/test/unittests/rpc/Web3RpcTest.cpp
> +        params2->addAddress(std::move(*toHexString(address1)));
修改为toHexStringWithPrefix

2024-05-07 06:54 UTC, kyonRay submitted a review, later dismissed

2024-05-08 09:34 UTC, JimmyShi22 approved these changes

2024-05-08 11:58 UTC, merged